version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      cargo-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "cddl"