name: Continuous Integration

permissions: read-all

on:
  merge_group:
  pull_request:
  push:
    branches: 'main'

jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Rust
        run: rustup update stable && rustup default stable
      - name: Run tests
        run: cargo test

